### ISSUE TITLE
Project can't run.

### ISSUE THREAD

**Issue by Rifat977** [hossainchisty/FreshGerium-ERP-Platform#45]
python manage.py runserver
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.

How can i fix it?

**Comment by its-nihal-patel** [comment]
> python manage.py runserver CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
> 
> How can i fix it?

yeah man.. i have been trying to run this project but i am facing the same issue. moreover the developer didnt even give instructions how to install etc. i think he is not maintaining this repository anymore
